import {useMemo,useState} from 'react';
import {ArrowLeft,CalendarCheck,ChevronLeft,ChevronRight,Clock3,Save,Trash2,Trophy} from 'lucide-react';
import {useApp} from '../hooks/useApp';
import {getExercise} from '../data/exercises';
import {calendarStatus,estimateWorkoutDuration,getProgramInfo,getSuggestedWorkoutId,localIso,logKey,sessionsForDate} from '../utils/trainingPlan';
import type {CalendarStatus,Session,SetLog,Status,Workout} from '../types';

const statuses:CalendarStatus[]=['suggerito','selezionato','in-corso','completato','parziale','saltato','riposo'];
const statusLabels:Record<CalendarStatus,string>={suggerito:'Suggerito',selezionato:'Selezionato','in-corso':'In corso',completato:'Completato',parziale:'Parziale',saltato:'Saltato',riposo:'Riposo',neutro:'Neutro'};
const numberOrNull=(value:string)=>value===''?null:Number(value);

export default function Calendar(){
  const {data,setData}=useApp(); const [month,setMonth]=useState(new Date()); const [selected,setSelected]=useState(localIso()); const [detailId,setDetailId]=useState<string>();
  const year=month.getFullYear(),monthIndex=month.getMonth(),days=new Date(year,monthIndex+1,0).getDate(),first=(new Date(year,monthIndex,1).getDay()+6)%7;
  const cells=[...Array(first).fill(null),...Array.from({length:days},(_,index)=>index+1)];const dateKey=(day:number)=>`${year}-${String(monthIndex+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;
  const daySessions=sessionsForDate(selected,data);const active=data.activeSession?.date===selected?data.activeSession:null;const hasSelection=Object.prototype.hasOwnProperty.call(data.plannedDates,selected);
  const explicitSelection=hasSelection?data.plannedDates[selected]:'';const suggestedId=getSuggestedWorkoutId(data);const state=calendarStatus(selected,data);const showSuggestion=selected===localIso()&&state==='neutro';
  const plannedWorkout=data.workouts.find(workout=>workout.id===(explicitSelection&&explicitSelection!=='riposo'?explicitSelection:showSuggestion?suggestedId:undefined));const info=getProgramInfo(data,selected);
  const detailSession=data.sessions.find(session=>session.id===detailId);
  const monthStats=useMemo(()=>{const states=Array.from({length:days},(_,index)=>calendarStatus(dateKey(index+1),data));return {completed:states.filter(value=>value==='completato').length,selected:states.filter(value=>['selezionato','in-corso'].includes(value)).length,skipped:states.filter(value=>value==='saltato').length};},[data,days,year,monthIndex]);
  const setPlan=(value:string)=>setData(current=>{const plannedDates={...current.plannedDates};if(!value)delete plannedDates[selected];else plannedDates[selected]=value as Workout['id']|'riposo';return {...current,plannedDates};});
  const updateSession=(id:string,update:(session:Session)=>Session)=>setData(current=>({...current,sessions:current.sessions.map(session=>session.id===id?update(session):session)}));
  const changeHistoricalSet=(session:Session,key:string,index:number,change:Partial<SetLog>)=>updateSession(session.id,current=>({...current,logs:{...current.logs,[key]:(current.logs[key]||[]).map((set,setIndex)=>setIndex===index?{...set,...change}:set)}}));
  const deleteSession=(session:Session)=>{if(!confirm(`Eliminare definitivamente ${session.workoutName||'questa seduta'} del ${session.date}?`))return;setData(current=>({...current,sessions:current.sessions.filter(item=>item.id!==session.id)}));setDetailId(undefined);};
  const changeDateTime=(session:Session,value:string)=>{const timestamp=new Date(value).getTime();if(Number.isNaN(timestamp))return;const date=value.slice(0,10);updateSession(session.id,current=>({...current,date,startedAt:timestamp}));setSelected(date);};

  if(detailSession){return <>
    <header className="history-detail-header"><button className="back-button" onClick={()=>setDetailId(undefined)}><ArrowLeft/> Torna al calendario</button><span className="eyebrow">Seduta registrata</span><h1>{detailSession.workoutShort||detailSession.workoutId.toUpperCase()} · {detailSession.workoutName||'Allenamento storico'}</h1><p className="lede">Identificatore stabile: {detailSession.id.slice(0,8)}</p></header>
    <section className="card history-editor"><div className="history-meta-grid"><label>Data e ora<input type="datetime-local" value={new Date(detailSession.startedAt||`${detailSession.date}T12:00`).toLocaleString('sv-SE').slice(0,16)} onChange={event=>changeDateTime(detailSession,event.target.value)}/></label><label>Durata effettiva<input type="number" inputMode="numeric" min="0" value={detailSession.duration} onChange={event=>updateSession(detailSession.id,current=>({...current,duration:Number(event.target.value)}))}/></label><label>Stato<select value={detailSession.status} onChange={event=>updateSession(detailSession.id,current=>({...current,status:event.target.value as Status}))}><option value="completato">Completato</option><option value="parziale">Parziale</option><option value="saltato">Saltato</option><option value="recuperato">Recuperato</option></select></label><label>RPE<input type="number" inputMode="numeric" min="1" max="10" value={detailSession.rpe??''} onChange={event=>updateSession(detailSession.id,current=>({...current,rpe:numberOrNull(event.target.value)}))}/></label></div><label>Note della seduta<textarea value={detailSession.notes} onChange={event=>updateSession(detailSession.id,current=>({...current,notes:event.target.value}))} placeholder="Correggi o aggiungi note"/></label><p className="save-indicator"><Save/> Le modifiche vengono salvate immediatamente.</p></section>
    {(detailSession.exercises||[]).map((item,itemIndex)=>{const exercise=getExercise(item.exerciseId,data.customExercises);const key=logKey(item);const sets=detailSession.logs[key]||[];const substituted=item.baseExerciseId&&item.baseExerciseId!==item.exerciseId;return <article className="card historical-exercise" key={`${key}-${itemIndex}`}><div className="section-title"><div><span className="eyebrow">{!item.baseExerciseId?'Aggiunto durante la seduta':substituted?'Sostituzione':'Esercizio previsto'}</span><h2>{exercise?.name||item.exerciseId}</h2></div><span>{sets.filter(set=>set.done).length}/{sets.length} serie</span></div>{substituted&&<p>Sostituisce: {getExercise(item.baseExerciseId!,data.customExercises)?.name||item.baseExerciseId}</p>}<div className="history-set-list">{sets.map((set,index)=><div className="history-set" key={index}><b>{set.warmup?'R':index+1}</b><label>kg<input type="number" inputMode="decimal" step="0.5" value={set.weight??''} onChange={event=>changeHistoricalSet(detailSession,key,index,{weight:numberOrNull(event.target.value)})}/></label><label>Rip.<input type="number" inputMode="numeric" value={set.reps??set.seconds??''} onChange={event=>changeHistoricalSet(detailSession,key,index,item.seconds?{seconds:numberOrNull(event.target.value)}:{reps:numberOrNull(event.target.value)})}/></label><label>RIR<input type="number" inputMode="numeric" min="0" max="10" value={set.rir??''} onChange={event=>changeHistoricalSet(detailSession,key,index,{rir:numberOrNull(event.target.value)})}/></label><label className="history-done"><input type="checkbox" checked={set.done} onChange={event=>changeHistoricalSet(detailSession,key,index,{done:event.target.checked})}/>Fatta</label><input className="history-note" value={set.notes} onChange={event=>changeHistoricalSet(detailSession,key,index,{notes:event.target.value})} placeholder="Nota serie"/></div>)}</div></article>;})}
    {detailSession.conditioning.length>0&&<section className="card"><h2>Conditioning</h2>{detailSession.conditioning.map(item=><div className="history-conditioning" key={item.id}><b>{item.activity}</b><span>{item.minutes??'—'} min · {item.distance??'—'} km · {item.calories??'—'} kcal manuali</span><p>{item.notes}</p></div>)}</section>}
    {(detailSession.records||[]).length>0&&<section className="card records-earned"><h2><Trophy/> Record personali</h2>{detailSession.records!.map(record=><p key={record}>{record}</p>)}</section>}
    <button className="danger-session" onClick={()=>deleteSession(detailSession)}><Trash2/> Elimina registrazione</button>
  </>}

  return <>
    <header><span className="eyebrow">Storico reale, nessun giorno fisso</span><h1>Calendario</h1><p className="lede">Consulta tutte le sedute, programma il futuro e correggi lo storico senza perdere le sessioni dello stesso giorno.</p></header>
    <section className="plan-banner card"><CalendarCheck/><div><b>Settimana {info.displayWeek} di 6 · {info.phase}</b><p>{info.objective} RIR target {info.rirTarget}.</p></div></section>
    <section className="calendar-summary"><span><b>{monthStats.completed}</b> giorni completati</span><span><b>{monthStats.selected}</b> selezionati</span><span><b>{monthStats.skipped}</b> saltati</span></section>
    <section className="calendar card"><div className="month"><button className="icon" onClick={()=>setMonth(new Date(year,monthIndex-1,1))}><ChevronLeft/></button><h2>{new Intl.DateTimeFormat('it-IT',{month:'long',year:'numeric'}).format(month)}</h2><button className="icon" onClick={()=>setMonth(new Date(year,monthIndex+1,1))}><ChevronRight/></button></div><div className="week">{['L','M','M','G','V','S','D'].map((label,index)=><b key={index}>{label}</b>)}</div><div className="days">{cells.map((day,index)=>{if(!day)return <i key={index}/>;const date=dateKey(day),cellState=calendarStatus(date,data),count=sessionsForDate(date,data).length;return <button key={index} onClick={()=>{setSelected(date);setDetailId(undefined)}} className={selected===date?'selected':''}><span>{day}</span>{cellState!=='neutro'&&<i className={cellState}/>} {count>1&&<small className="session-count">{count}</small>}</button>;})}</div><div className="legend">{statuses.map(value=><span key={value}><i className={value}/>{statusLabels[value]}</span>)}</div></section>
    <section className="card day-detail"><span className="eyebrow">{new Date(`${selected}T12:00`).toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</span><div className="calendar-edit-grid"><label>Programma una seduta<select value={explicitSelection} disabled={Boolean(active)} onChange={event=>setPlan(event.target.value)}><option value="">Nessuna scelta</option>{data.workouts.map(workout=><option key={workout.id} value={workout.id}>{workout.short} — {workout.name}</option>)}<option value="riposo">Riposo</option></select></label><div><small>Stato automatico</small><span className={`pill ${state}`}>{statusLabels[state]}</span></div></div>
      {plannedWorkout&&<div className="planned-session"><div className="day-title"><div><h2>{plannedWorkout.short} · {plannedWorkout.name}</h2>{showSuggestion&&<p><span className="pill suggerito">Suggerito</span> Il giorno resta neutro finché non scegli.</p>}</div><b>{estimateWorkoutDuration(plannedWorkout)}</b></div><p>{plannedWorkout.focus}</p></div>}
      {explicitSelection==='riposo'&&<><h2>Riposo</h2><p>Non conta come allenamento saltato e non riduce l’aderenza.</p></>}
      {daySessions.length>0&&<section className="day-sessions"><div className="section-title"><h2>Sedute registrate</h2><span>{daySessions.length}</span></div>{daySessions.map(session=><button className="history-session-card" key={session.id} onClick={()=>setDetailId(session.id)}><div><span className={`pill ${session.status==='recuperato'?'completato':session.status}`}>{session.status}</span><h3>{session.workoutShort||session.workoutId.toUpperCase()} · {session.workoutName||data.workouts.find(item=>item.id===session.workoutId)?.name}</h3><p><Clock3/> {new Date(session.startedAt||`${session.date}T12:00`).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})} · {session.duration} minuti · {(session.exercises||[]).length} esercizi</p></div><ChevronRight/></button>)}</section>}
      {!plannedWorkout&&explicitSelection!=='riposo'&&!daySessions.length&&<><h2>Giorno neutro</h2><p>Nessun allenamento selezionato: non influisce sull’aderenza e non diventa automaticamente saltato.</p></>}
    </section>
  </>;
}
