import {ImagePlus,Plus,Search,X} from 'lucide-react';
import {useMemo,useState} from 'react';
import {exerciseLibrary} from '../data/exercises';
import {useApp} from '../hooks/useApp';
import type {Exercise} from '../types';
import ExerciseArt from '../components/ExerciseArt';
import ExerciseModal from '../components/ExerciseModal';

const emptyForm={name:'',group:'',equipment:'',description:'',sets:'3',reps:'10–12',rest:'75',loaded:true,imageDataUrl:''};

export default function Exercises(){
  const {data,setData}=useApp();const [q,setQ]=useState('');const [group,setGroup]=useState('Tutti');const [equipment,setEquipment]=useState('Tutte');const [detail,setDetail]=useState<Exercise>();const [creating,setCreating]=useState(false);const [form,setForm]=useState(emptyForm);
  const all=useMemo(()=>exerciseLibrary(data.customExercises),[data.customExercises]);const groups=['Tutti',...Array.from(new Set(all.map(e=>e.group))).sort()];const equipmentOptions=['Tutte',...Array.from(new Set(all.map(e=>e.equipment))).sort()];
  const list=all.filter(e=>(group==='Tutti'||e.group===group)&&(equipment==='Tutte'||e.equipment===equipment)&&`${e.name} ${e.group} ${e.equipment}`.toLowerCase().includes(q.toLowerCase()));
  const loadImage=(file?:File)=>{if(!file)return;if(file.size>1_500_000){alert('L’immagine è troppo grande. Scegli un file inferiore a 1,5 MB per non appesantire i dati locali.');return;}const reader=new FileReader();reader.onload=()=>setForm(current=>({...current,imageDataUrl:String(reader.result)}));reader.readAsDataURL(file);};
  const createExercise=()=>{if(!form.name.trim()||!form.group.trim()||!form.equipment.trim()){alert('Inserisci nome, gruppo muscolare e attrezzatura.');return;}const exercise:Exercise={id:`custom-${crypto.randomUUID()}`,name:form.name.trim(),group:form.group.trim(),equipment:form.equipment.trim(),level:'Personalizzato',kind:'strength',loaded:form.loaded,sets:Math.max(1,Number(form.sets)||1),reps:form.reps.trim()||'10–12',rest:Math.max(0,Number(form.rest)||0),startPosition:form.description.trim()||'Assumi una posizione stabile e prepara l’attrezzatura in sicurezza.',endPosition:'Completa il movimento nell’escursione controllabile e ritorna lentamente.',steps:[form.description.trim()||'Prepara una posizione stabile.', 'Esegui il movimento con controllo.', 'Mantieni l’allineamento e interrompi in caso di dolore.'],breathing:'Espira durante lo sforzo e inspira nel ritorno.',mistakes:'Evita slancio, compensi e carichi che impediscono il controllo.',muscles:form.group.trim(),machineSetup:`Regola ${form.equipment.trim()} in base alla tua corporatura e verifica i fermi.`,safety:'Usa un carico controllabile e chiedi assistenza se non conosci l’attrezzatura.',custom:true,imageDataUrl:form.imageDataUrl||undefined,visualVerified:Boolean(form.imageDataUrl)};setData(current=>({...current,customExercises:[...current.customExercises,exercise]}));setForm(emptyForm);setCreating(false);setDetail(exercise);};
  return <><header><span className="eyebrow">Tecnica, alternative e sicurezza</span><h1>Esercizi</h1><p className="lede">{all.length} esercizi disponibili, inclusi quelli creati da te.</p><label className="search"><Search/><input value={q} onChange={event=>setQ(event.target.value)} placeholder="Cerca esercizio, muscolo o attrezzatura"/></label><div className="library-filter-row"><select value={group} onChange={event=>setGroup(event.target.value)}>{groups.map(value=><option key={value}>{value}</option>)}</select><select value={equipment} onChange={event=>setEquipment(event.target.value)}>{equipmentOptions.map(value=><option key={value}>{value}</option>)}</select></div><button className="primary create-exercise" onClick={()=>setCreating(true)}><Plus/> Crea esercizio</button></header>
    {creating&&<section className="card custom-exercise-form"><div className="section-title"><h2>Nuovo esercizio</h2><button className="icon" onClick={()=>setCreating(false)} aria-label="Chiudi"><X/></button></div><div className="custom-fields"><label>Nome<input value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label><label>Gruppo muscolare<input value={form.group} onChange={event=>setForm({...form,group:event.target.value})}/></label><label>Attrezzatura<input value={form.equipment} onChange={event=>setForm({...form,equipment:event.target.value})}/></label><label>Serie predefinite<input type="number" inputMode="numeric" min="1" value={form.sets} onChange={event=>setForm({...form,sets:event.target.value})}/></label><label>Ripetizioni predefinite<input value={form.reps} onChange={event=>setForm({...form,reps:event.target.value})}/></label><label>Recupero secondi<input type="number" inputMode="numeric" min="0" value={form.rest} onChange={event=>setForm({...form,rest:event.target.value})}/></label><label className="custom-description">Descrizione<textarea value={form.description} onChange={event=>setForm({...form,description:event.target.value})} placeholder="Descrivi posizione e movimento"/></label><label className="loaded-toggle"><input type="checkbox" checked={form.loaded} onChange={event=>setForm({...form,loaded:event.target.checked})}/> Registra un carico in kg</label><label className="image-upload"><ImagePlus/> Immagine facoltativa, max 1,5 MB<input type="file" accept="image/*" onChange={event=>loadImage(event.target.files?.[0])}/></label>{form.imageDataUrl&&<img className="custom-preview" src={form.imageDataUrl} alt="Anteprima esercizio personalizzato"/>}</div><button className="primary" onClick={createExercise}>Salva esercizio</button></section>}
    <div className="exercise-grid">{list.map(e=><button className="library-card card" onClick={()=>setDetail(e)} key={e.id}><ExerciseArt id={e.id} name={e.name} verified={e.visualVerified} imageDataUrl={e.imageDataUrl}/><span className="eyebrow">{e.group}{e.custom?' · Personalizzato':''}</span><h2>{e.name}</h2><p>{e.level} · {e.equipment}</p>{e.visualVerified===false&&!e.imageDataUrl&&<small className="unverified-note">Dimostrazione visiva non ancora verificata</small>}</button>)}</div>{!list.length&&<p className="empty card">Nessun esercizio corrisponde ai filtri.</p>}{detail&&<ExerciseModal e={detail} onClose={()=>setDetail(undefined)}/>}</>;
}
