import {useEffect,useMemo,useState} from 'react';
import {ArrowDown,ArrowUp,CircleCheck,Minus,Pause,Play,Plus,Repeat2,RotateCcw,Search,SkipForward,TrendingUp,X} from 'lucide-react';
import {useApp} from '../hooks/useApp';
import {conditioningActivities,defaultConditioning,emptyLogs,emptySet} from '../data/defaults';
import {exerciseLibrary,getExercise} from '../data/exercises';
import {canProgress,estimateWorkoutDuration,exerciseSets,getProgramInfo,getSuggestedWorkoutId,isCompleted,isRecordedTraining,localIso,logKey,repRangeMax,sessionCompletion,sessionVolume} from '../utils/trainingPlan';
import ExerciseArt from '../components/ExerciseArt';
import ExerciseModal from '../components/ExerciseModal';
import type {ActiveSession,ConditioningActivity,Exercise,Session,SetLog,Workout,WorkoutExercise} from '../types';

const numberOrNull=(value:string)=>value===''?null:Number(value);
const activityExerciseIds:Record<ConditioningActivity,string>={'Camminata':'walk','Camminata inclinata':'incline-walk','Vogatore':'rower','Cyclette':'bike','Ellittica':'elliptical','Stair Climber':'stair-climber','Boxe':'boxing','Corda':'jump-rope'};
const prioritizedEquipment=(equipment:string)=>/macchina|machine|cavo|lat |leg |pec deck|row/i.test(equipment)?0:/corpo|tappetino/i.test(equipment)?1:2;
const replacementPools:Record<string,string[]>={
  bike:['rower','elliptical','walk','incline-walk'],
  rower:['bike','elliptical','walk','incline-walk'],
  'chest-press':['converging-chest-press','incline-chest-press','pec-deck','cable-chest-fly'],
  'incline-chest-press':['converging-chest-press','chest-press','cable-chest-fly','pec-deck'],
  'converging-chest-press':['chest-press','incline-chest-press','pec-deck','cable-chest-fly'],
  'seated-row':['iso-lateral-row-machine','cable-row','machine-high-row'],
  'iso-lateral-row-machine':['seated-row','cable-row','machine-high-row'],
  'shoulder-press':['lateral-raise','lateral-cable','cable-front-raise'],
  'lat-machine':['neutral-grip-pulldown','single-arm-lat-pulldown','assisted-pull-up'],
  'neutral-grip-pulldown':['lat-machine','single-arm-lat-pulldown','assisted-pull-up'],
  'lateral-cable':['lateral-raise','cable-front-raise'],
  'triceps-pushdown':['overhead-triceps-cable','triceps-extension-machine','cable-triceps-kickback'],
  'leg-press':['pendulum-squat-machine','hack-squat','single-leg-press','bodyweight-squat'],
  'seated-leg-curl':['lying-leg-curl','leg-curl'],
  'leg-extension':['pendulum-squat-machine','hack-squat','single-leg-press','step-up'],
  'glute-drive-machine':['hip-thrust','glute-bridge','glute-machine','glute-kickback-cable'],
  'front-plank':['kneeling-cable-crunch','dead-bug','hollow-hold','side-plank','ab-crunch'],
  'reverse-pec-deck':['rear-delt-cable'],
  'curl-cable':['preacher-curl-machine','curl-machine','rope-hammer-curl'],
};
type IndexedExercise={item:WorkoutExercise;index:number};

function resolvedExercises(workout:Workout,substitutions:Record<string,string>,library:Exercise[]):WorkoutExercise[] {
  return workout.exercises.map(item=>{const replacement=substitutions[item.exerciseId];return {...item,instanceId:crypto.randomUUID(),baseExerciseId:item.exerciseId,exerciseId:replacement&&library.some(exercise=>exercise.id===replacement)?replacement:item.exerciseId};});
}

export default function Today(){
  const {data,setData}=useApp(); const today=localIso(); const active=data.activeSession?.date===today?data.activeSession:null;
  const library=useMemo(()=>exerciseLibrary(data.customExercises),[data.customExercises]);
  const explicitChoice=data.plannedDates[today]; const suggestedId=getSuggestedWorkoutId(data); const chosenId=active?.workoutId || (explicitChoice!=='riposo'?explicitChoice:undefined);
  const workout=data.workouts.find(item=>item.id===chosenId); const suggestedWorkout=data.workouts.find(item=>item.id===suggestedId)!;
  const todaySessions=data.sessions.filter(session=>session.date===today).sort((a,b)=>(b.startedAt||0)-(a.startedAt||0));
  const [chooserOpen,setChooserOpen]=useState(!chosenId&&explicitChoice!=='riposo'); const [detail,setDetail]=useState<Exercise>();
  const [replacement,setReplacement]=useState<{index:number;nextId:string;future:boolean}|null>(null); const [addOpen,setAddOpen]=useState(false);
  const [addSearch,setAddSearch]=useState(''); const [addGroup,setAddGroup]=useState('Tutti'); const [addEquipment,setAddEquipment]=useState('Tutte');
  const [selectedToAdd,setSelectedToAdd]=useState<string[]>([]); const [addToDefault,setAddToDefault]=useState(false);
  const [rest,setRest]=useState(0); const [restPaused,setRestPaused]=useState(false); const [,setTick]=useState(0); const phase=getProgramInfo(data,today);

  useEffect(()=>{if(!rest||restPaused)return;const timer=window.setTimeout(()=>setRest(value=>value-1),1000);if(rest===1&&navigator.vibrate)navigator.vibrate([180,80,180]);return()=>window.clearTimeout(timer);},[rest,restPaused]);
  useEffect(()=>{if(!active||active.pausedAt)return;const timer=window.setInterval(()=>setTick(value=>value+1),1000);return()=>window.clearInterval(timer);},[active?.startedAt,active?.pausedAt]);
  const elapsedSeconds=active?Math.max(0,Math.floor(((active.pausedAt||Date.now())-active.startedAt-active.pausedMs)/1000)):0;
  const progress=active?sessionCompletion(active):{done:0,total:0,percent:0};

  const dashboard=useMemo(()=>{const start=new Date(`${today}T12:00:00`);start.setDate(start.getDate()-((start.getDay()+6)%7));const weekStart=localIso(start);
    const sessions=data.sessions.filter(session=>session.date>=weekStart&&session.date<=today);const completed=sessions.filter(session=>isCompleted(session.status)).length;
    const recorded=sessions.filter(session=>isRecordedTraining(session.status)).length;const last=[...data.sessions].filter(session=>isRecordedTraining(session.status)).sort((a,b)=>(b.completedAt||0)-(a.completedAt||0)||b.date.localeCompare(a.date))[0];
    const body=[...data.bodyRecords].filter(item=>item.weight!==null).sort((a,b)=>b.date.localeCompare(a.date))[0];const improvements=sessions.reduce((sum,session)=>sum+(session.exercises||[]).filter(item=>getExercise(item.exerciseId,data.customExercises)?.loaded&&canProgress(session,item.exerciseId,data)).length,0);
    return {sessions:completed,recorded,minutes:sessions.reduce((sum,session)=>sum+session.duration,0),volume:Math.round(sessions.reduce((sum,session)=>sum+sessionVolume(session),0)),last,body,improvements};},[data,today]);

  const updateActive=(update:(draft:ActiveSession)=>ActiveSession)=>setData(current=>current.activeSession?{...current,activeSession:update(current.activeSession)}:current);
  const choose=(choice:Workout['id']|'riposo')=>{if(active)return;setData(current=>({...current,plannedDates:{...current.plannedDates,[today]:choice}}));setChooserOpen(false);};
  const begin=()=>{if(!workout)return;const exercises=resolvedExercises(workout,data.preferredSubstitutions,library);setData(current=>({...current,plannedDates:{...current.plannedDates,[today]:workout.id},activeSession:{id:crypto.randomUUID(),date:today,workoutId:workout.id,startedAt:Date.now(),pausedAt:null,pausedMs:0,exercises,separatedSupersets:[],logs:workout.id==='e'?{}:emptyLogs(exercises),conditioning:workout.id==='e'?defaultConditioning():[],notes:'',rpe:null}}));};
  const togglePause=()=>updateActive(draft=>draft.pausedAt?{...draft,pausedMs:draft.pausedMs+Date.now()-draft.pausedAt,pausedAt:null}:{...draft,pausedAt:Date.now()});
  const changeSet=(key:string,index:number,change:Partial<SetLog>)=>updateActive(draft=>({...draft,logs:{...draft.logs,[key]:(draft.logs[key]||[]).map((set,setIndex)=>setIndex===index?{...set,...change}:set)}}));
  const toggleSet=(key:string,index:number,restSeconds:number)=>{const set=active?.logs[key]?.[index];if(!set)return;changeSet(key,index,{done:!set.done});if(!set.done&&data.preferences.autoRest&&restSeconds){setRest(restSeconds);setRestPaused(false);}};
  const updateExercise=(index:number,change:Partial<WorkoutExercise>)=>updateActive(draft=>({...draft,exercises:draft.exercises.map((item,i)=>i===index?{...item,...change}:item)}));
  const moveExercise=(index:number,direction:-1|1)=>updateActive(draft=>{const destination=index+direction;if(destination<0||destination>=draft.exercises.length)return draft;const exercises=[...draft.exercises];[exercises[index],exercises[destination]]=[exercises[destination],exercises[index]];return {...draft,exercises};});
  const removeExercise=(index:number)=>{if(!active||!confirm('Rimuovere questo esercizio dalla sessione?'))return;updateActive(draft=>{const item=draft.exercises[index];const logs={...draft.logs};delete logs[logKey(item)];return {...draft,exercises:draft.exercises.filter((_,i)=>i!==index),logs};});};
  const addSet=(item:WorkoutExercise,warmup=false)=>{const key=logKey(item);updateActive(draft=>({...draft,logs:{...draft.logs,[key]:[...(draft.logs[key]||[]),emptySet(warmup)]},exercises:draft.exercises.map(row=>logKey(row)===key?{...row,sets:(draft.logs[key]?.filter(set=>!set.warmup).length||0)+(warmup?0:1)}:row)}));};
  const removeSet=(item:WorkoutExercise,index:number)=>{const key=logKey(item);updateActive(draft=>{const sets=(draft.logs[key]||[]).filter((_,i)=>i!==index);return {...draft,logs:{...draft.logs,[key]:sets},exercises:draft.exercises.map(row=>logKey(row)===key?{...row,sets:sets.filter(set=>!set.warmup).length}:row)};});};

  const alternativesFor=(exercise:Exercise,itemIndex:number)=>{const curated=replacementPools[exercise.id];return library.filter(candidate=>candidate.id!==exercise.id&&(curated?curated.includes(candidate.id):candidate.group===exercise.group)&&(candidate.visualVerified!==false||Boolean(candidate.imageDataUrl))&&!active?.exercises.some((item,index)=>index!==itemIndex&&item.exerciseId===candidate.id)).sort((a,b)=>{const aRank=curated?.indexOf(a.id)??-1;const bRank=curated?.indexOf(b.id)??-1;return aRank>=0&&bRank>=0?aRank-bRank:prioritizedEquipment(a.equipment)-prioritizedEquipment(b.equipment)||a.name.localeCompare(b.name)});};
  const applyReplacement=()=>{if(!active||!replacement)return;setData(current=>{const currentActive=current.activeSession;if(!currentActive)return current;const item=currentActive.exercises[replacement.index];if(!item)return current;const baseId=item.baseExerciseId||item.exerciseId;return {...current,preferredSubstitutions:replacement.future?{...current.preferredSubstitutions,[baseId]:replacement.nextId}:current.preferredSubstitutions,activeSession:{...currentActive,exercises:currentActive.exercises.map((row,index)=>index===replacement.index?{...row,exerciseId:replacement.nextId,baseExerciseId:baseId}:row)}};});setReplacement(null);};
  const filteredLibrary=useMemo(()=>library.filter(exercise=>(addGroup==='Tutti'||exercise.group===addGroup)&&(addEquipment==='Tutte'||exercise.equipment===addEquipment)&&`${exercise.name} ${exercise.group} ${exercise.equipment}`.toLowerCase().includes(addSearch.toLowerCase())),[library,addSearch,addGroup,addEquipment]);
  const addExercises=()=>{if(!active||!selectedToAdd.length)return;setData(current=>{const currentActive=current.activeSession;if(!currentActive)return current;const additions=selectedToAdd.map(id=>{const exercise=getExercise(id,current.customExercises);return {exerciseId:id,instanceId:crypto.randomUUID(),sets:exercise.sets,reps:exercise.reps,seconds:exercise.seconds,rest:exercise.rest};});const logs={...currentActive.logs};additions.forEach(item=>{logs[logKey(item)]=Array.from({length:item.sets},()=>emptySet());});const next={...current,activeSession:{...currentActive,exercises:[...currentActive.exercises,...additions],logs}};if(addToDefault)next.workouts=current.workouts.map(row=>row.id===currentActive.workoutId?{...row,exercises:[...row.exercises,...additions.map(({instanceId,...item})=>item)]}:row);return next;});setSelectedToAdd([]);setAddOpen(false);setAddToDefault(false);};

  const previousBest=(exerciseId:string)=>Math.max(0,...data.sessions.flatMap(session=>exerciseSets(session,exerciseId).filter(set=>set.done&&!set.warmup).map(set=>set.weight||0)));
  const lastPerformance=(exerciseId:string)=>{const previous=[...data.sessions].sort((a,b)=>(b.completedAt||0)-(a.completedAt||0)||b.date.localeCompare(a.date)).find(session=>exerciseSets(session,exerciseId).some(set=>set.done&&(set.reps!==null||set.seconds!==null)));if(!previous)return null;const best=[...exerciseSets(previous,exerciseId).filter(set=>set.done)].sort((a,b)=>(b.weight||0)-(a.weight||0))[0];if(!best)return null;return best.weight!==null?`Ultima volta: ${best.weight} kg × ${best.reps??'—'}`:`Ultima volta: ${best.reps??best.seconds??'—'}${best.seconds!==null?' sec':''}`;};
  const sessionRecords=()=>active?.exercises.flatMap(item=>{const exercise=getExercise(item.exerciseId,data.customExercises);if(!exercise.loaded)return[];const best=Math.max(0,...(active.logs[logKey(item)]||[]).filter(set=>set.done&&!set.warmup).map(set=>set.weight||0));return best>previousBest(item.exerciseId)?[`${exercise.name}: nuovo carico ${best} kg`]:[];})||[];
  const finish=()=>{if(!active||!workout)return;const completion=sessionCompletion(active);const session:Session={id:active.id,date:today,workoutId:active.workoutId,workoutName:workout.name,workoutShort:workout.short,startedAt:active.startedAt,completedAt:Date.now(),status:completion.percent===100?'completato':'parziale',duration:Math.max(1,Math.round(elapsedSeconds/60)),notes:active.notes,rpe:active.rpe,logs:active.logs,conditioning:active.conditioning,exercises:active.exercises,records:sessionRecords()};setData(current=>{const plannedDates={...current.plannedDates};delete plannedDates[today];return {...current,plannedDates,sessions:[...current.sessions,session],activeSession:null};});};
  const skip=()=>{if(!workout)return;const reason=prompt('Motivo (tempo, stanchezza, dolore, lavoro, viaggio, altro):','mancanza di tempo');if(reason===null)return;const session:Session={id:crypto.randomUUID(),date:today,workoutId:workout.id,workoutName:workout.name,workoutShort:workout.short,startedAt:Date.now(),completedAt:Date.now(),status:'saltato',duration:0,notes:'',rpe:null,reason,logs:{},conditioning:[],exercises:resolvedExercises(workout,data.preferredSubstitutions,library),records:[]};setData(current=>{const plannedDates={...current.plannedDates};delete plannedDates[today];return {...current,plannedDates,sessions:[...current.sessions,session]};});};
  const updateConditioning=(id:string,field:string,value:string|boolean)=>updateActive(draft=>({...draft,conditioning:draft.conditioning.map(item=>item.id===id?{...item,[field]:typeof value==='boolean'?value:field==='activity'||field==='notes'?value:numberOrNull(value)}:item)}));
  const moveConditioning=(index:number,direction:-1|1)=>updateActive(draft=>{const destination=index+direction;if(destination<0||destination>=draft.conditioning.length)return draft;const conditioning=[...draft.conditioning];[conditioning[index],conditioning[destination]]=[conditioning[destination],conditioning[index]];return {...draft,conditioning};});
  const activeCanProgress=(item:WorkoutExercise,exercise:Exercise)=>{const max=repRangeMax(item.reps);const sets=(active?.logs[logKey(item)]||[]).filter(set=>!set.warmup);return phase.phase!=='Scarico'&&exercise.loaded&&Boolean(max&&sets.length&&sets.every(set=>set.done&&set.reps!==null&&set.reps>=max&&set.rir!==null&&set.rir>=2));};

  const renderExercise=(entry:IndexedExercise)=>{if(!active)return null;const {item,index:itemIndex}=entry;const exercise=getExercise(item.exerciseId,data.customExercises);const key=logKey(item);const sets=active.logs[key]||[];const previous=lastPerformance(exercise.id);const alternatives=alternativesFor(exercise,itemIndex);let workNumber=0;return <article className="set-card card" key={key}>
    <div className="session-exercise-head"><ExerciseArt id={exercise.id} name={exercise.name} verified={exercise.visualVerified} imageDataUrl={exercise.imageDataUrl}/><div><span className="eyebrow">{exercise.group}</span><h2>{exercise.name}</h2><p>{item.reps?`${item.reps} ripetizioni`:`${item.seconds} secondi`} · recupero {item.rest||'—'}s</p>{previous&&<small className="last-performance">{previous}</small>}<div className="exercise-actions"><button className="text-btn" onClick={()=>setDetail(exercise)}>Come si esegue</button><button className="text-btn" disabled={!alternatives.length} onClick={()=>alternatives[0]&&setReplacement({index:itemIndex,nextId:alternatives[0].id,future:false})}>Sostituisci</button></div></div><div className="exercise-order"><button className="icon" disabled={itemIndex===0} onClick={()=>moveExercise(itemIndex,-1)} aria-label={`Sposta ${exercise.name} su`}><ArrowUp/></button><button className="icon" disabled={itemIndex===active.exercises.length-1} onClick={()=>moveExercise(itemIndex,1)} aria-label={`Sposta ${exercise.name} giù`}><ArrowDown/></button><button className="icon danger" onClick={()=>removeExercise(itemIndex)} aria-label={`Rimuovi ${exercise.name}`}><X/></button></div></div>
    <div className="exercise-config"><label>Target<input value={item.reps||item.seconds||''} onChange={event=>updateExercise(itemIndex,item.seconds?{seconds:event.target.value}:{reps:event.target.value})}/></label><label>Recupero sec<input type="number" inputMode="numeric" min="0" value={item.rest} onChange={event=>updateExercise(itemIndex,{rest:Number(event.target.value)})}/></label></div>
    {replacement?.index===itemIndex&&<div className="replacement-panel"><label>Alternativa pertinente<select value={replacement.nextId} onChange={event=>setReplacement({...replacement,nextId:event.target.value})}>{alternatives.map(candidate=><option key={candidate.id} value={candidate.id}>{candidate.name} · {candidate.equipment}</option>)}</select></label><label className="future-replacement"><input type="checkbox" checked={replacement.future} onChange={event=>setReplacement({...replacement,future:event.target.checked})}/> Usa questa sostituzione anche in futuro</label><div><button className="primary" onClick={applyReplacement}>Applica</button><button className="secondary" onClick={()=>setReplacement(null)}>Annulla</button></div></div>}
    <div className={`set-grid-head ${exercise.loaded?'has-weight':'no-weight'} ${exercise.kind==='strength'?'has-rir':'no-rir'}`}><span>Serie</span>{exercise.loaded&&<span>Peso kg</span>}<span>{item.seconds?'Secondi':'Ripet.'}</span>{exercise.kind==='strength'&&<span>RIR</span>}<span>Fatto</span></div>
    {sets.map((set,setIndex)=>{if(!set.warmup)workNumber+=1;const displayNumber=set.warmup?'R':workNumber;return <div className="set-block" key={setIndex}><div className={`gym-set ${exercise.loaded?'has-weight':'no-weight'} ${exercise.kind==='strength'?'has-rir':'no-rir'}`}><b>{displayNumber}</b>{exercise.loaded&&<input aria-label={`Peso serie ${displayNumber}`} inputMode="decimal" type="number" min="0" step="0.5" placeholder="—" value={set.weight??''} onChange={event=>changeSet(key,setIndex,{weight:numberOrNull(event.target.value)})}/>}<input aria-label={`Valore serie ${displayNumber}`} inputMode="numeric" type="number" min="0" placeholder="—" value={(item.seconds?set.seconds:set.reps)??''} onChange={event=>changeSet(key,setIndex,item.seconds?{seconds:numberOrNull(event.target.value)}:{reps:numberOrNull(event.target.value)})}/>{exercise.kind==='strength'&&<input aria-label={`RIR serie ${displayNumber}`} inputMode="numeric" type="number" min="0" max="10" placeholder="—" value={set.rir??''} onChange={event=>changeSet(key,setIndex,{rir:numberOrNull(event.target.value)})}/>}<button className={set.done?'done':'check'} onClick={()=>toggleSet(key,setIndex,item.rest)} aria-label={`Completa serie ${displayNumber}`}><CircleCheck/></button><input className="set-note" aria-label={`Note serie ${displayNumber}`} placeholder="Nota opzionale" value={set.notes} onChange={event=>changeSet(key,setIndex,{notes:event.target.value})}/></div><div className="set-meta"><label><input type="checkbox" checked={Boolean(set.warmup)} onChange={event=>changeSet(key,setIndex,{warmup:event.target.checked})}/> Riscaldamento</label><button onClick={()=>removeSet(item,setIndex)} disabled={sets.length<=1}><Minus/> Rimuovi serie</button></div></div>})}
    <div className="set-add-actions"><button className="secondary" onClick={()=>addSet(item)}><Plus/> Serie</button><button className="secondary" onClick={()=>addSet(item,true)}><Plus/> Riscaldamento</button></div>
    {activeCanProgress(item,exercise)&&<p className="progression-tip"><TrendingUp/> Range completato con almeno 2 RIR: nella prossima seduta valuta un aumento del 2,5–5%, mantenendo la tecnica.</p>}
  </article>;};

  const groups=['Tutti',...Array.from(new Set(library.map(exercise=>exercise.group))).sort()]; const equipment=['Tutte',...Array.from(new Set(library.map(exercise=>exercise.equipment))).sort()];

  return <>
    <header><span className="eyebrow">{new Intl.DateTimeFormat('it-IT',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</span><h1>{active?'Allenamento in corso':'Oggi'}</h1><p className="lede">Due sedute Upper complete, una Lower + Core e conditioning facoltativo. A privilegia la spinta, C la tirata; B le separa per favorire il recupero.</p></header>
    {!active&&<>
      <section className="phase-card card"><TrendingUp/><div><span className="eyebrow">Settimana {phase.displayWeek} di 6 · {phase.phase}</span><h3>RIR target {phase.rirTarget}</h3><p>{phase.objective}</p></div></section>
      <section className="dashboard-grid"><article><b>{dashboard.sessions||'—'}</b><span>Completati settimana</span></article><article><b>{dashboard.recorded||'—'}</b><span>Sedute registrate</span></article><article><b>{dashboard.minutes||'—'}</b><span>Minuti totali</span></article><article><b>{dashboard.volume?`${dashboard.volume} kg`:'—'}</b><span>Volume totale</span></article></section>
      <section className="card dashboard-detail"><div><small>Ultima sessione reale</small><b>{dashboard.last?`${dashboard.last.workoutShort||dashboard.last.workoutId.toUpperCase()} · ${dashboard.last.date}`:'Nessun dato registrato.'}</b></div><div><small>Prossimo suggerimento forza</small><b>{suggestedWorkout.short} · {suggestedWorkout.name}</b></div><div><small>Ultimo peso corporeo</small><b>{dashboard.body?`${dashboard.body.weight} kg`:'Nessun dato registrato.'}</b></div><div><small>Miglioramenti recenti</small><b>{dashboard.improvements?`${dashboard.improvements} range completati`:'Nessun dato registrato.'}</b></div></section>
      <section className="suggested-workout card"><div><span className="eyebrow">Allenamento suggerito oggi</span><h2>{suggestedWorkout.short} — {suggestedWorkout.name}</h2><p>Rotazione A → B → C. Il conditioning E è facoltativo e non interrompe la sequenza.</p></div><span className="pill suggerito">Consigliato</span></section>
      <button className="primary choose-workout" onClick={()=>setChooserOpen(value=>!value)}><Repeat2/> Scegli allenamento</button>
      {chooserOpen&&<section className="workout-chooser card"><div className="section-title"><h2>Scegli liberamente</h2><button className="icon" onClick={()=>setChooserOpen(false)} aria-label="Chiudi scelta"><X/></button></div><div className="workout-choice-grid">{data.workouts.map(item=><button key={item.id} onClick={()=>choose(item.id)} className={item.id===suggestedId?'recommended':''}><b>{item.short}</b><span>{item.name}</span>{item.id===suggestedId&&<small>Consigliato</small>}</button>)}<button className="rest-choice" onClick={()=>choose('riposo')}><b>Riposo</b><span>Registra recupero</span></button></div></section>}
      {todaySessions.length>0&&<section className="card today-history"><div className="section-title"><h2>Sedute di oggi</h2><span>{todaySessions.length}</span></div>{todaySessions.map(session=><div key={session.id}><b>{session.workoutShort||session.workoutId.toUpperCase()} · {session.workoutName}</b><span>{session.status} · {session.duration} min · {new Date(session.startedAt||`${session.date}T12:00`).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}</span></div>)}<p>Lo storico completo è disponibile in Progressi.</p></section>}
      {explicitChoice==='riposo'?<section className="rest-day card"><span className="pill riposo">Riposo</span><h2>Oggi hai scelto Riposo</h2><p>Puoi comunque scegliere una seduta se cambi programma.</p></section>:workout?<><section className="hero card"><div><span className="pill selezionato">Selezionato</span><h2>Allenamento di oggi: {workout.short}</h2><p>{workout.name} · {workout.focus}</p></div><strong>{estimateWorkoutDuration(workout).replace(' min','')}<small> min</small></strong><div className="selection-context"><small>Allenamento suggerito</small><b>{suggestedWorkout.short} — {suggestedWorkout.name}</b></div><div className="hero-actions"><button className="primary" onClick={begin}><Play/> Inizia allenamento</button><button className="secondary" onClick={()=>setChooserOpen(true)}><Repeat2/> Cambia</button><button className="secondary" onClick={skip}><SkipForward/> Segna saltato</button></div></section><section><div className="section-title"><h2>La sessione</h2><span>{workout.exercises.length} esercizi</span></div>{workout.exercises.map((item,index)=>{const exercise=getExercise(item.exerciseId,data.customExercises);return <article className="exercise-row" key={`${exercise.id}-${index}`}><ExerciseArt id={exercise.id} name={exercise.name} verified={exercise.visualVerified} imageDataUrl={exercise.imageDataUrl}/><div><span className="eyebrow">{index===0?'Riscaldamento':exercise.group}</span><h3>{exercise.name}</h3><p>{item.sets>1?`${item.sets} × `:''}{item.reps?`${item.reps} rip.`:`${Number(item.seconds||0)/60} min`}{item.rest?` · recupero ${item.rest}s`:''}</p><button className="text-btn" onClick={()=>setDetail(exercise)}>Tecnica e regolazione</button></div></article>})}</section></>:<section className="neutral-day card"><h2>Nessun allenamento selezionato</h2><p>Scegli una seduta quando vuoi allenarti.</p></section>}
    </>}

    {active&&workout&&<>
      <section className="workout-head card"><div className="ring" style={{'--pct':`${progress.percent*3.6}deg`} as React.CSSProperties}><b>{progress.percent}%</b></div><div><span className="eyebrow">{active.pausedAt?'In pausa':'Sessione attiva'}</span><h2>{workout.short} · {workout.name}</h2><p>{progress.done} di {progress.total} elementi · {Math.floor(elapsedSeconds/60)}:{String(elapsedSeconds%60).padStart(2,'0')}</p></div><button className="icon timer-pause" onClick={togglePause} aria-label={active.pausedAt?'Riprendi':'Pausa'}>{active.pausedAt?<Play/>:<Pause/>}</button></section>
      {rest>0&&<aside className="rest"><RotateCcw/><div><small>RECUPERO</small><b>{Math.floor(rest/60)}:{String(rest%60).padStart(2,'0')}</b></div><button className="icon" onClick={()=>setRestPaused(value=>!value)}>{restPaused?<Play/>:<Pause/>}</button><button className="icon" onClick={()=>setRest(0)}><X/></button></aside>}
      <div className="timer-controls"><div className="quick-rest"><span>Timer</span>{[30,45,60,75,90,120].map(seconds=><button onClick={()=>{setRest(seconds);setRestPaused(false)}} key={seconds}>{seconds}s</button>)}</div><label className="auto-rest-toggle"><input type="checkbox" checked={data.preferences.autoRest} onChange={event=>setData(current=>({...current,preferences:{...current.preferences,autoRest:event.target.checked}}))}/><span>Timer automatico dopo ogni serie</span></label></div>
      {workout.id!=='e'&&<button className="primary add-exercise-main" onClick={()=>setAddOpen(true)}><Plus/> Aggiungi esercizio</button>}
      {addOpen&&<section className="card add-exercise-panel"><div className="section-title"><h2>Aggiungi esercizi</h2><button className="icon" onClick={()=>setAddOpen(false)} aria-label="Chiudi libreria"><X/></button></div><div className="library-filters"><label><Search/> <input placeholder="Cerca" value={addSearch} onChange={event=>setAddSearch(event.target.value)}/></label><select value={addGroup} onChange={event=>setAddGroup(event.target.value)}>{groups.map(value=><option key={value}>{value}</option>)}</select><select value={addEquipment} onChange={event=>setAddEquipment(event.target.value)}>{equipment.map(value=><option key={value}>{value}</option>)}</select></div><div className="add-library-list">{filteredLibrary.map(exercise=><label key={exercise.id}><input type="checkbox" checked={selectedToAdd.includes(exercise.id)} onChange={event=>setSelectedToAdd(current=>event.target.checked?[...current,exercise.id]:current.filter(id=>id!==exercise.id))}/><span><b>{exercise.name}</b><small>{exercise.group} · {exercise.equipment}</small></span></label>)}</div><label className="future-replacement"><input type="checkbox" checked={addToDefault} onChange={event=>setAddToDefault(event.target.checked)}/> Aggiorna anche la scheda predefinita</label><button className="primary" disabled={!selectedToAdd.length} onClick={addExercises}>Aggiungi {selectedToAdd.length||''} alla sessione</button></section>}

      {workout.id!=='e'&&<section className="standalone-exercises"><div className="section-title"><h2>Esercizi della seduta</h2><span>Uno alla volta</span></div>{active.exercises.map((item,index)=>renderExercise({item,index}))}</section>}
      {workout.id==='e'&&<section className="conditioning-list">{active.conditioning.map((item,index)=>{const exercise=getExercise(activityExerciseIds[item.activity],data.customExercises);return <article className="conditioning-card card" key={item.id}><div className="conditioning-visual"><ExerciseArt id={exercise.id} name={exercise.name} verified={exercise.visualVerified}/><div><span className="eyebrow">Attività {index+1}</span><h2>{item.activity}</h2><button className="text-btn" onClick={()=>setDetail(exercise)}>Come si esegue</button></div></div><div className="conditioning-title"><div className="reorder-buttons"><button className="icon" disabled={index===0} onClick={()=>moveConditioning(index,-1)} aria-label={`Sposta ${item.activity} su`}><ArrowUp/></button><button className="icon" disabled={index===active.conditioning.length-1} onClick={()=>moveConditioning(index,1)} aria-label={`Sposta ${item.activity} giù`}><ArrowDown/></button></div><select aria-label={`Attività ${index+1}`} value={item.activity} onChange={event=>updateConditioning(item.id,'activity',event.target.value as ConditioningActivity)}>{conditioningActivities.map(activity=><option key={activity}>{activity}</option>)}</select><button aria-label={`Completa attività ${index+1}`} className={item.done?'done':'check'} onClick={()=>updateConditioning(item.id,'done',!item.done)}><CircleCheck/></button></div><div className="conditioning-fields"><label>Minuti<input type="number" inputMode="numeric" min="0" value={item.minutes??''} onChange={event=>updateConditioning(item.id,'minutes',event.target.value)}/></label><label>Distanza km<input type="number" inputMode="decimal" min="0" step="0.01" value={item.distance??''} onChange={event=>updateConditioning(item.id,'distance',event.target.value)}/></label><label>Round<input type="number" inputMode="numeric" min="0" value={item.intensity??''} onChange={event=>updateConditioning(item.id,'intensity',event.target.value)}/></label><label>Calorie macchina<input type="number" inputMode="numeric" min="0" value={item.calories??''} onChange={event=>updateConditioning(item.id,'calories',event.target.value)}/></label></div><textarea placeholder="Intensità e note" value={item.notes} onChange={event=>updateConditioning(item.id,'notes',event.target.value)}/><button className="remove-row" onClick={()=>updateActive(draft=>({...draft,conditioning:draft.conditioning.filter(row=>row.id!==item.id)}))}>Rimuovi attività</button></article>})}<button className="secondary add-activity" onClick={()=>updateActive(draft=>({...draft,conditioning:[...draft.conditioning,{id:crypto.randomUUID(),activity:'Camminata',minutes:null,distance:null,calories:null,intensity:null,notes:'',done:false}]}))}><Plus/> Aggiungi attività</button></section>}
      <section className="card session-notes"><label>RPE sessione (opzionale)<input inputMode="numeric" type="number" min="1" max="10" value={active.rpe??''} onChange={event=>updateActive(draft=>({...draft,rpe:numberOrNull(event.target.value)}))}/></label><label>Note allenamento<textarea placeholder="Sensazioni, tecnica, fastidi…" value={active.notes} onChange={event=>updateActive(draft=>({...draft,notes:event.target.value}))}/></label></section><div className="finish"><button className="primary" onClick={finish}>Termina e salva allenamento</button><button className="secondary" onClick={togglePause}>{active.pausedAt?'Riprendi allenamento':'Metti in pausa'}</button></div>
    </>}
    {detail&&<ExerciseModal e={detail} onClose={()=>setDetail(undefined)}/>}
  </>;
}
